version: '3'
services:
  influxdb:
    image: influxdb
    restart: always
    environment:
      - INFLUXDB_USER=usuario
      - INFLUXDB_PASSWORD=contraseña
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - grafana-net
    ports:
    - 8086:8086
  grafana:
    image: grafana/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=usuario
      - GF_SECURITY_ADMIN_PASSWORD=contraseña
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - grafana-net
    ports:
      - 3000:3000
networks:
  grafana-net: